{{- define "datree-lib.clusterrolebinding" -}}
{{- if .Values.rbac.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.rbac.clusterRole.name}} 
  labels: {{include "datree.labels" . | nindent 4}}
  {{- if .Values.customAnnotations }}
  annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.rbac.clusterRole.name}} # datree-webhook-server-read
subjects:
  - kind: ServiceAccount
    name: {{.Values.rbac.serviceAccount.name}} # datree-webhook-server
    namespace: {{template "datree.namespace" .}}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datree-namespaces-update
  labels: {{include "datree.labels" . | nindent 4}}
  {{- if .Values.customAnnotations }}
  annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datree-namespaces-update
subjects:
  - kind: ServiceAccount
    name: "datree-label-namespaces-hook-post-install"
    namespace: "{{template "datree.namespace" .}}"
  - kind: ServiceAccount
    name: "datree-cleanup-namespaces-hook-pre-delete"
    namespace: "{{template "datree.namespace" .}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datree-validationwebhook-delete
  labels: {{include "datree.labels" . | nindent 4}}
  {{- if .Values.customAnnotations }}
  annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datree-validationwebhook-delete
subjects:
  - kind: ServiceAccount
    name: "datree-cleanup-namespaces-hook-pre-delete"
    namespace: "{{template "datree.namespace" .}}"
